### ISSUE TITLE
[Drupal] Refine README so installation goes smoothly

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#1]
Mentioned by Lowell if I recall correctly that the README needs some work, and the installation procedure may be revamped and improved with new Drupal methodology.

**Comment by Lowell20** [comment]
I believe the readme is correct, but it assumes you have a working server environment for a drupal site.
Basically php 5.6(minimum), a mysql database server, and a webserver (nginx or apache)

**Comment by AnthonyAstige** [comment]
In working on #2 I wonder about this section:

![do we really want to delete the drupal-project folder then why a git hard reset shouldn t we use the code in our rpeository](https://cloud.githubusercontent.com/assets/236039/14587292/7e594300-0476-11e6-8ee1-b7626d14408f.png)

It doesn't seem right to
1. delete the repo code in a development setup
2. Use a git reset --hard

**Comment by AnthonyAstige** [comment]
There may be a broken dependency; when I run `composer install` it seems to fail cloning `git@github.com:Lowell20/auto_nodetitle.git`.

This could be related to the fact that I didn't create a fresh project as noted in above comment

![screenshot from 2016-04-17 08-36-08](https://cloud.githubusercontent.com/assets/236039/14587360/72481cfc-0477-11e6-92c9-8a750197e76b.png)

**Comment by Lowell20** [comment]
referring to previous 2 comments,
1. the rm -rf and reset --hard are workarounds until we can find a better way. They are necessary because the post-install script fails to setup the correct environment otherwise.
2. the git clone is failing because of github authentication, we can change the git@github.com: to https://github.com/  in the composer.json file, and it should then `composer install` should work fine

**Comment by AnthonyAstige** [comment]
> the git clone is failing because of github authentication, we can change the git@github.com: to https://github.com/ in the composer.json file, and it should then composer install should work fine

I updated in 09ae91a but looks like I got the same error.  Maybe I did it wrong.

![screenshot from 2016-04-17 09-59-15](https://cloud.githubusercontent.com/assets/236039/14587979/19dc72c8-0483-11e6-8075-cda9bfd4bf8b.png)

> the rm -rf and reset --hard are workarounds until we can find a better way. They are necessary because the post-install script fails to setup the correct environment otherwise.

What's the post-install script? Do you have details on what specifically it sets up incorrectly?

**Comment by Lowell20** [comment]
ah, yes, you will need to update the composer.lock with this command
`composer update drupal/auto_nodetitle`

**Comment by AnthonyAstige** [comment]
In continuing work on #2, I'm getting an error when running the step at `drush si --account-pass=admin -y` as shown attached.

![2016-04-17_2126](https://cloud.githubusercontent.com/assets/236039/14592344/26880f22-04e3-11e6-885d-82d6b26e51e2.png)

The error message given doesn't seem to tell me any specific PHP extension(s) that need enabling.

**Comment by Lowell20** [comment]
I would look to see that the basic drupal setup requirements are met. These error messages aren't going to indicate true cause until the install is successful. 
1. Did you do the drupal create-project step after rm -rf drupal project?
2. Is there a web/sites/default/settings.php file?
3. Does it have the database credentials it needs?
   1. If you have drush working, you can try `drush st` from the web directory to see if it sees the database correctly.

These are getting into a lot of drupal specifics, complete books are written to address these cases.
I can walk you through a troubleshooting though, and get you up and running in a few minutes, lets connect whenever you have time.

**Comment by AnthonyAstige** [comment]
I sanity checked and the answer to all question 1-3 above is 'Yes'.

RE 3.i. - Here's the output I get for `drush st` (and some other version checking):

![screenshot from 2016-04-18 08-35-48](https://cloud.githubusercontent.com/assets/236039/14605940/92507ef8-0540-11e6-82cf-89d2e6b080e0.png)

You can read [/drupal-project/bin/vmsquickinstall.sh](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/bin/vmsquickinstall.sh) to see the installation steps taken.  

You're right it's probably something you'll see easily given your Drupal experience, that would take me hours without it. I'll be at the C4EC meetup tonight and we can troubleshoot together then.  Thanks~

**Comment by AnthonyAstige** [comment]
The VMS install script works now, which is good enough for me.  Closing this.
