### ISSUE TITLE
Address policy.drush.inc

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#10]
File pops up after vmsinstall on a fresh machine

Add to repo or gitignore?

![2016-04-25_2336](https://cloud.githubusercontent.com/assets/236039/14807092/9830e778-0b3e-11e6-9e3c-913e6362b61d.png)

**Comment by Lowell20** [comment]
I think it should already be ignored

**Comment by AnthonyAstige** [comment]
**Reproduction**

I used these instructions to reproduce the issue (just now / again)
1. http://vms.codeforeauclaire.org/ >> Spun up new machine
2. Followed steps 1 & 2 in [VMS development enviornment quick setup instructions](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/README.md#vms-development-enviornment-quick-setup-instructions)
   1. Before step 1: I deleted my fork
3. From ssh of vms server `(cd /root/foodtrucks && git status)`

Resulting (new) screenshot

![screenshot from 2016-04-26 19-44-21](https://cloud.githubusercontent.com/assets/236039/14838496/4f82d5dc-0be7-11e6-9725-6efa058c5ffa.png)

**Thoughts**

Maybe related to [vmsquickinstall.sh hard reset](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/bin/vmsquickinstall.sh#L70)

**Comment by Lowell20** [comment]
Yeah, I see that it is not in the .gitignore list
but since I don't know how it got there I don't know what the correct action will be.
my drupal installations have only a README.md file in that directory

can you determine how it got there?

**Comment by AnthonyAstige** [comment]
I just did another full run through and looks like composer is creating the file.

**Reproduction summary**

`drupal-project/drush/policy.drush.inc` is ...
1. generated from `composer create-project drupal-composer/drupal-project:8.x-dev drupal-project --stability dev --no-interaction`
2. isolated with `git reset --hard HEAD`

**Reproduction details from scratch**
1. http://vms.codeforeauclaire.org/ >> Spin up new machine
2. Prep server by from initial code in [/drupal-project/bin/vmsquickinstall.sh](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/bin/vmsquickinstall.sh)
   1. Everything before `git clone ...` on line 65 (Put into [setup.txt](https://github.com/codeforeauclaire/foodtrucks/files/239640/setup.txt))
3. Run `git clone https://github.com/codeforeauclaire/foodtrucks.git /root/foodtrucks`
4. Run more commands from [/drupal-project/bin/vmsquickinstall.sh](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/bin/vmsquickinstall.sh), between each running `(cd /root/foodtrucks && git status)` to check for `policy.drush.inc`
   1. `(cd /root/foodtrucks && rm -rf drupal-project)`
   2. `(cd /root/foodtrucks && composer create-project drupal-composer/drupal-project:8.x-dev drupal-project --stability dev --no-interaction)`
      1. I see `drupal-project/drush/policy.drush.inc` untracked along with a ton of other untracked and deleted files
   3. `(cd /root/foodtrucks && git reset --hard HEAD)`
      1. I now see an untracked `drupal-project/drush/policy.drush.inc` without finishing [/drupal-project/bin/vmsquickinstall.sh](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/bin/vmsquickinstall.sh)

**Comment by Lowell20** [comment]
Added this file to the repo

**Comment by AnthonyAstige** [comment]
Confirmed: Git status is now clean after vms installation.
