### ISSUE TITLE
[Drupal] remove website schema fields / add validating logic at the json level

### ISSUE THREAD

**Issue by aaronsalmon** [codeforeauclaire/foodtrucks#100]

**Comment by AnthonyAstige** [comment]
I'm not sure what this is, but it sounds like something important (put in MVP) and on the Drupal side (assigned to Lowell).  If I'm mistaken in anywhere feel free to adjust.

**Comment by Lowell20** [comment]
this is totally inert, non-blocking 
just some fields we've decided we don't need after all, the validation routine seems to be sufficient

**Comment by Lowell20** [comment]
b8e4b8b
