### ISSUE TITLE
[Consumer] remove "no events" popup on any click.

### ISSUE THREAD

**Issue by aaronsalmon** [codeforeauclaire/foodtrucks#101]

**Comment by AnthonyAstige** [comment]
I wasn't there tonight so I'm not 100% sure what this is, but it sounds important (MVP) and like something Levi (assigned) can handle.  If I'm mistaken in any way please correct.

**Comment by aaronsalmon** [comment]
this is smoother now. it doesn't prohibit  you from interacting with date selection arrows
