### ISSUE TITLE
[Consumer] Make top menu 'Trucks' and 'About' links work when there is a "no events" popup present.

### ISSUE THREAD

**Issue by aaronsalmon** [codeforeauclaire/foodtrucks#109]
currently if there is a "no events" popup open, you can't click on those two top links. let's have those links cancel the no events popup instead.

**Comment by aaronsalmon** [comment]
actually if there is a "no events" popup active, you can't trigger the calendar too... maybe that no-events popup should hide on any click at all.

**Comment by levifelling** [comment]
Caused by https://github.com/codeforeauclaire/foodtrucks/commit/7ec6559999e7e48ec2ebf703f3f3dfd43f25303e

Previous behavior was clicking anywhere outside of popup would close popup.

**Comment by aaronsalmon** [comment]
shoot. yeah my hack screwed things up.... sorry about that!   I didn't like the extra click when trying to rapidly date-switch but maybe it's not worth the hassle

**Comment by levifelling** [comment]
I reverted https://github.com/codeforeauclaire/foodtrucks/commit/7ec6559999e7e48ec2ebf703f3f3dfd43f25303e
to fix this issue
