### ISSUE TITLE
Cleanup: Remove OriginalREADME.md?

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#11]
https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/OriginalREADME.md

**Comment by Lowell20** [comment]
I think there is some good info in here about the base drupal project.
Maybe a different name for the file?

**Comment by AnthonyAstige** [comment]
@Lowell20 - Is OriginalREADME.md the file that comes by default with a Drupal installation?

**Comment by Lowell20** [comment]
It is the default README for this composer project, which is managing our
Drupal installation.
It is not the default method for installing and managing a Drupal 8 install

**Comment by AnthonyAstige** [comment]
@Lowell20 Addressed @ https://github.com/codeforeauclaire/foodtrucks/commit/84cb2bc7ef27330d7fcc099f782e0502a4b818f4. If I mispoke in the README, etc feel free to tweak my solution.
