### ISSUE TITLE
[Drupal] Get images data into repository >> update install script to put them somewhere

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#15]
![2016-05-09_2107](https://cloud.githubusercontent.com/assets/236039/15133615/1fa29b2a-162a-11e6-8d1e-93b3e12cd029.png)

@Lowell20 - Once the data is in there reassign to me and I'll update the install script.

**Comment by Lowell20** [comment]
@AnthonyAstige let me know if you want to work on this tonight
I can set up a folder in the repo for the image files and database and then we just need to move those files to the right location after the site scaffolding is in place

**Comment by AnthonyAstige** [comment]
@Lowell20 It's not urgent (I've put all time sensitive issues in the MVP milestone), but whenever you get a chance yeah get the images in.

**Comment by Lowell20** [comment]
this is been done
