### ISSUE TITLE
[Drupal] MVP API

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#18]
The [Consumer] side needs this data / api to work
- [x] Basic events list
- [x] Well formatted dates (**Canceled w/#25 comment 9:45pm**)
- [x] Filter by date **Note May 23rd: Filter by Eau Claire's time, watch out for off by timezone errors**
- [x] Ensure all needed data included for #5

**Comment by Lowell20** [comment]
@AnthonyAstige do you know if we will want to filter by a date range or maybe, to keep it simple, just individual dates. For example, the consumer side could send multiple requests, one for each date it needs data for. This is just a thought, just let me know what you think you will be looking for

**Comment by AnthonyAstige** [comment]
@Lowell20 Just one date at a time sounds good for the MVP.

@aaronsalmon - See Lowell's prior comment, in case you're wire framing up something we may have a need for a date range search soon.

**Comment by AnthonyAstige** [comment]
@Lowell20 - The api gives dates like "2016-05-04T01:30:00".  It looks like UTC, but we think [UTC usually has a Z at the end](https://stackoverflow.com/questions/2002891/what-do-you-call-a-date-time-with-a-t-in-the-middle-2008-09-18t000000).  We need to be sure we're [doing the right stuff with times/timezones](https://github.com/codeforeauclaire/foodtrucks/issues/25).  Can you confirm it's a standard time format and let us know how to identify the timezone, and/or patch it?

**Comment by Lowell20** [comment]
restructured a few things, here is the beginning of the endpoints naming, including a vendor endpoint
http://vendors.foodtrucks.codeforeauclaire.org/api/vendors
http://vendors.foodtrucks.codeforeauclaire.org/api/events
http://vendors.foodtrucks.codeforeauclaire.org/api/events/date-or-timestamp

**Comment by Lowell20** [comment]
I can confirm it is UTC time

**Comment by AnthonyAstige** [comment]
What's the difference between these:
1. http://vendors.foodtrucks.codeforeauclaire.org/api/events
2. http://vendors.foodtrucks.codeforeauclaire.org/api/events/date-or-timestamp

**Comment by Lowell20** [comment]
I think my goal is to filter the results by a date or date range, the "date-or-timestamp" text can be replaced  with the query parameters.
Right now it is just a placeholder until we know what kinds of parameters we will be sending through

**Comment by levifelling** [comment]
For the MVP we would need API endpoints for:
1. all events (useful for dev, but not required for MVP)
  http://vendors.foodtrucks.codeforeauclaire.org/api/events
2. events where start_time or end_time is on the given day
  http://vendors.foodtrucks.codeforeauclaire.org/api/events/{date UTC}
  http://vendors.foodtrucks.codeforeauclaire.org/api/events/2016-05-26T00:00:00
3. a single event by uuid
  http://vendors.foodtrucks.codeforeauclaire.org/api/events/{uuid}
  http://vendors.foodtrucks.codeforeauclaire.org/api/events/5ec386b2-a9f8-4a79-9b46-f9e9aff1fd08

I'm no too particular on how you want to format the API so long as we can get access to the data.

**Comment by AnthonyAstige** [comment]
RE: 2. Simpler and more clear I think to just have the date with no time in the url imo. ie;
http://vendors.foodtrucks.codeforeauclaire.org/api/events/2016-05-26

RE: 3. I'm not sure we need single event query in the API for the MVP -  https://github.com/codeforeauclaire/foodtrucks/issues/30 can easily retrieve by date and filter locally by Event UUID.  (https://github.com/codeforeauclaire/foodtrucks/issues/38 for [lodash](https://lodash.com/) opened to help here)

**Comment by AnthonyAstige** [comment]
We have enough in the API now I think for MVP.  Issues will fall out while coding as needed from here.
