### ISSUE TITLE
[Drupal] Setup hosting

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#21]
The drupal hosting needs some thought the best place / way to host the Drupal site.

We have the vms quick install script, not sure of it's production quality.

The only server we have is that one free ec2 server. Perhaps we should just pay for a single Digital Ocean droplet to do this on.  Perhaps we should just host it on Lowell's stuff since he hosts Drupal stuff already.

**Comment by AnthonyAstige** [comment]
@Lowell20 Would you be willing to handle the hosting for the production foodtrucks Drupal site?  Am I correct to assume it would be pretty easy for you to setup alongside your normally hosted Drupal stuff on an existing server?

**Background**
- I could set it up on the free ec2 server I'm sure, but that muddies that environment
- There's a potential to get hosting from CodeForAmerica, which may change our options in the future, so I figure good to just get things up and running quickly for now.

**Comment by AnthonyAstige** [comment]
Fom @aaronsalmon in Slack

> Where will the Drupal vendor admin live?

In case we need to [share cookies between the sites](https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain) for single sign on or the like, we should use a subdomain like vendors.foodtrucks.codeforeauclaire.org.

**Comment by Lowell20** [comment]
I'm ok with hosting as needed. The current IP address is 104.237.143.35 . I will add the http://vendors.foodtrucks.codeforeauclaire.org configuration right now, so point that name to this IP at any time

**Comment by AnthonyAstige** [comment]
@Lowell20 - Great, thanks!

@aaronsalmon - Need DNS from you here to point vendors.foodtrucks.codeforeauclaire.org to 104.237.143.35.

**Comment by aaronsalmon** [comment]
added!

**Comment by AnthonyAstige** [comment]
@Lowell20 - DNS is up and running, but hosting adjustments needed.

![2016-05-23_2126](https://cloud.githubusercontent.com/assets/236039/15490395/21d86fe2-212d-11e6-8c2e-91b146c4f98d.png)

**Comment by Lowell20** [comment]
Lol, I forgot to restart the server. Working now
