### ISSUE TITLE
[Consumer] Empty map - Fix regression from 04e6b59?

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#23]
https://github.com/codeforeauclaire/foodtrucks/commit/04e6b59235d92773efb0d1e951ed163eb47ae266 makes nothing shows up on the map for me when using `/consumer-ui/bin/serve`.

**Edit**
Commit comment in https://github.com/codeforeauclaire/foodtrucks/commit/04e6b59235d92773efb0d1e951ed163eb47ae266 references https://github.com/codeforeauclaire/foodtrucks/issues/22, maybe the local test data needs updating?

**Background**
I regression tested via `git checkout master && git checkout HEAD~N` (Replacing N until I idenditifed N-1 worked, and N didn't, where N pointed to 04e6b59)

**Comment by levifelling** [comment]
This commit included the date filter functionality, so the lack of anything on the map is because we are by default filtering to only show locations for the current date. I did add the ability to bypass the filter and show all events by add `#all` to the URL http://localhost:3000/#all

**Comment by AnthonyAstige** [comment]
Ah nice.  I've documented in the serve script now, closing this issue.
