### ISSUE TITLE
[Drupal] Fix API missing data?

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#29]
From loading http://foodtrucks1.version-three.com/default-endpoint

![2016-05-23_1933](https://cloud.githubusercontent.com/assets/236039/15488570/4761142c-211d-11e6-9075-4b476a7ef342.png)

**Comment by Lowell20** [comment]
resolved, this happens when an event is not associated with a foodtruck.
I have added a filter to hide the event if it is not properly associated
