### ISSUE TITLE
Create vendors endpoint

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#36]
For https://github.com/codeforeauclaire/foodtrucks/issues/28

Lowell's question:

> can we decide on sane url's for these endpoints?

Perhaps a url for this would be something like `/vendors`?

**Comment by Lowell20** [comment]
restructured a few things, here is the beginning of the endpoints naming, including a vendor endpoint
http://vendors.foodtrucks.codeforeauclaire.org/api/vendors
http://vendors.foodtrucks.codeforeauclaire.org/api/events
http://vendors.foodtrucks.codeforeauclaire.org/api/events/date-or-timestamp
