### ISSUE TITLE
Cleanup external repository dependencies

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#39]
https://github.com/codeforeauclaire/foodtrucks/commit/cd6707c3e3b6b5540222241ab6699c42e6861249 links to repositories at https://gitlab.com/codeforeauclaire/

Simpler infrastructure if all foodtrucks code in a single repository.  Failing that, at least having all core dependencies on GitHub keeps source permissions sane.

**Comment by Lowell20** [comment]
Good idea. You might be responding to the repos I connected from a gitlab account.
This is temporary to facilitate development on my end.

**Comment by Lowell20** [comment]
Ok, moved foodtruckmodule, auto_nodetitle, and foodtruckstheme into their respective module and theme custom folders
