### ISSUE TITLE
[Consumer] Sync up with drupal json api changes

### ISSUE THREAD

**Issue by Lowell20** [codeforeauclaire/foodtrucks#40]
Because of several reasons, the food truck info will be nested inside the event info.
This will prevent overwriting the uuid's and allow multiple trucks per event.

![2016-05-29_1531](https://cloud.githubusercontent.com/assets/1144169/15635899/b5bf9bf2-25b2-11e6-88fb-abd60d922cef.png)

**Comment by Lowell20** [comment]
Looking at this output, I see that we might want "null" for missing values? Instead of just missing?
Examples:
the first event food truck has no logo
the second event food truck has no link

Just let me know if it makes more sense to have null values instead of missing values

**Comment by Lowell20** [comment]
ooh, and if we allow any multiple values in the admin entry forms, I will need to represent those as nested fields. 
Example: 
The links field is multiple. As it is, the link value will get overwritten by the last value in the mutliple value field if more that one link is entered.

I can fix this by restricting the entry form to only one link, or we can nest the links in the json like I just nested the truck info.

This will also apply to any other field that we allow multiple values for.

**Comment by AnthonyAstige** [comment]
> Looking at this output, I see that we might want "null" for missing values? Instead of just missing?

Missing is fine, JavaScript can easily check what fields are there. As a side benefit it keeps the noise & size down in case more results are returned in the future.

> if we allow any multiple values in the admin entry forms, I will need to represent those as nested fields. 

For the API an array instead of a single value should be clear for development.  That said the vendor UI should be kept fairly simple per [Aaron's Balsamic](https://github.com/codeforeauclaire/foodtrucks/issues/33); I think most if not all fields will be single entries.

**Comment by Lowell20** [comment]
ahh, yes. I see that he split the website url and facebook url into two different things

**Comment by Lowell20** [comment]
I've update the image above with changes made as a result of implementing admin ui features

**Comment by Lowell20** [comment]
links have been removed, and replaced with 
- [x] Website URL (website_url)
- [ ] Facebook URL (facebook_url)
- [ ] Twitter Name (twitter_name)

and name is replaced with
- [x] Title (title)

**Comment by Lowell20** [comment]
The checkmarks mean they are updated in the consumer js

**Comment by AnthonyAstige** [comment]
Lowell made a pass at this and things look ok at at a glance.  Also we have https://github.com/codeforeauclaire/foodtrucks/issues/6 open to catch anything else.
