### ISSUE TITLE
[Drupal] Triage misc

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#42]
Screenshots from today's discussion, some may already be done, check off as completed.  Only do what's quick and we'll see what's left over at the end.
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5 - http://stackoverflow.com/questions/8720931/can-css-detect-the-number-of-children-an-element-has may be helpful
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10

1
![1](https://cloud.githubusercontent.com/assets/236039/15658882/c542c74a-2687-11e6-8113-399a03eea8f2.png)

2
![2](https://cloud.githubusercontent.com/assets/236039/15658880/c5427aba-2687-11e6-9f18-61f884434619.png)

3
![3](https://cloud.githubusercontent.com/assets/236039/15658883/c543fd4a-2687-11e6-871b-32d8284fc523.png)

4
![4](https://cloud.githubusercontent.com/assets/236039/15658879/c542542c-2687-11e6-804b-40bf6dec134b.png)

5
![5](https://cloud.githubusercontent.com/assets/236039/15658881/c542c0f6-2687-11e6-9215-3435a9429d68.png)

6
![6](https://cloud.githubusercontent.com/assets/236039/15658884/c54445b6-2687-11e6-8d1f-2972e184115a.png)

7
![7](https://cloud.githubusercontent.com/assets/236039/15658885/c556e8ce-2687-11e6-8eff-dee495b2bb00.png)

8
![8](https://cloud.githubusercontent.com/assets/236039/15658888/c558a376-2687-11e6-8b08-2f03b6874ea6.png)

9
![9a](https://cloud.githubusercontent.com/assets/236039/15658887/c5579350-2687-11e6-80e5-d2d9ff450067.png)
![9b](https://cloud.githubusercontent.com/assets/236039/15658886/c5573590-2687-11e6-85f0-4f3067e13257.png)
![9c](https://cloud.githubusercontent.com/assets/236039/15658889/c55a0734-2687-11e6-9cf7-4079eb108695.png)
![9d](https://cloud.githubusercontent.com/assets/236039/15658890/c55b283a-2687-11e6-8b02-ed10bfffabe0.png)

10
![10](https://cloud.githubusercontent.com/assets/236039/15658891/c56def7e-2687-11e6-8d4e-cc4b62ac42cd.png)

**Comment by Lowell20** [comment]
#8 the green message banner is overlapping the header, need to style it below the header

**Comment by AnthonyAstige** [comment]
Assigning to self for review of work done by Lowell; a lot of details here.

**Comment by AnthonyAstige** [comment]
Spoke about this stuff a lot during meeting today and items fell out of discussion, closing.
