### ISSUE TITLE
[Drupal] Change Event Date and Time handling

### ISSUE THREAD

**Issue by Lowell20** [codeforeauclaire/foodtrucks#44]
To make similar to balsamics, I've changed the date to a year, month, date storage format.
This also makes searching by date much easier. 
Example:
/api/events/2016--5-31
will return any event with that date.
The times are handled as integers now with an hour field and a minute field.
Also a duration field

**Comment by Lowell20** [comment]
I haven't pushed to live site yet, oops, only one dash between year and month. 
Posting issue to share format requirements

**Comment by Lowell20** [comment]
I will close the issue when it is done

**Comment by AnthonyAstige** [comment]
Per our discussion on UTC yesterday, and the note about that the api request url doesn't include a precise time, I'm going to assume the API filters by local Eau Claire time.

**Comment by Lowell20** [comment]
If we implement this change to match the balsamic administration ui then
utc doesn't matter any more.

Dates are stored as y-m-d. Easy peasy

**Comment by AnthonyAstige** [comment]
Yeah makes sense, it simplifies a couple things for us.

**Comment by Lowell20** [comment]
ok, it is actuall yyyy-mm-dd, like 2016-06-01

**Comment by Lowell20** [comment]
the admin end is pushed to live environment, now the consumer needs to be adjusted to match

**Comment by Lowell20** [comment]
date: "2016-05-31",
duration: "120",
start_hour: "10",
start_minute: "0",

this json snippet shows today at 10:00am until 12:00noon

**Comment by AnthonyAstige** [comment]
> the admin end is pushed to live environment, now the consumer needs to be adjusted to match

Depending on the direction the conversation goes in https://github.com/codeforeauclaire/foodtrucks/issues/46#issuecomment-222836010.

In either case that's another issue, and sounds like the core of this one is done, so I'll close this one.  Feel free to re-open if I'm mistaken.
