### ISSUE TITLE
[Drupal] Make events API return timestamps

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#46]
After [#44 - [Drupal] Change Event Date and Time handling](https://github.com/codeforeauclaire/foodtrucks/issues/44) is done I think the API will by default return individual year/month/day/hour/minute values instead of timestamps. It's more "correct" to have timestamps, and best to get them formatted as such early as is reasonably possible in the data flow.

@Lowell20 If it's trouble to get the API to handle this, lets close this issue and open one to handle it on the [Consumer] side using moment (not hard to do).

Note: If the api changes the timestamp in any way (name, timezone, format, ...) we may have to make (probably trivial) [Consumer] adjustments to reflect.

**Comment by Lowell20** [comment]
I'm not sure what you are asking for. 
What format do you want to send the request in? 
It is not a problem to convert it to the required yyyy-mm-dd, but as-is the yyyy-mm-dd format works

**Comment by AnthonyAstige** [comment]
The url for the request is fine as /api/events/2016-06-01

I'm asking for the data returned JSON data to be timestamps, like

```
{
 ...
 start_time: 2016-05-29T03:00:00
...
}
```

**Comment by Lowell20** [comment]
I think this is now working as you described

**Comment by AnthonyAstige** [comment]
Yeah that looks good, thanks~

http://vendors.foodtrucks.codeforeauclaire.org/api/events/2016-06-01
![screenshot from 2016-05-31 19-35-01](https://cloud.githubusercontent.com/assets/236039/15694847/d243605a-2766-11e6-84d7-f0cf31c126a2.png)

**Comment by Lowell20** [comment]
duration is now converted to end_time
