### ISSUE TITLE
[Consumer] Adjust time parsing for new api

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#47]
Per recent comments in #46 we still have `start_time` and `duration` has replaced `end_time`.

Looks like this now
![screenshot from 2016-05-31 19-35-01](https://cloud.githubusercontent.com/assets/236039/15694883/4d7d5d2a-2767-11e6-8702-b69c9440852a.png)

Which of course needs the UI adjusted in a few ways as it looks like:

![screenshot from 2016-05-31 19-42-08](https://cloud.githubusercontent.com/assets/236039/15694928/d334156c-2767-11e6-959e-ee3df722d8d3.png)

Things I think may need adjustment
- [x] Date stamps in bubble
- [x] Open / closed check (shows up in bubble)
- [x] Color highlight on map for now / future (did we do that?)

**Comment by AnthonyAstige** [comment]
@Lowell20 Is `start_time` UTC?

**Comment by Lowell20** [comment]
it is not UTC. it is the date with the time of day appended to it. This is a consequence of storing the date and time as separate fields. It is local time, not managed by timezones at all.
Also, duration has been converted to end_time

**Comment by Lowell20** [comment]
per commit fc9cdc2. Simply offsetting by 5 hours will probably not work during daylight savings.
Can we disable timezone corrections in the js completely?
or... I can instead send a UTC timestamp if needed.

**Comment by AnthonyAstige** [comment]
Per [fc9cdc2 line #115](https://github.com/codeforeauclaire/foodtrucks/commit/fc9cdc2be9901e293700b51a88e6e0367635bee5#diff-1488a48aa588ab200ee0a1fdcdcc9db4R115) we do this time logic with the user's browser which takes DST into account, while the API doesn't. We need to take timezone into accounts to do date comparisons.

**Example** (Current state before patched)
1. Food Truck adds event every day for 5pm-6pm
2. User visits http://foodtrucks.codeforeauclaire.org/ at 6:30pm today
   1. [Drupal] API returns `end_time` of 6pm
   2. [Consumer] Browser interprets `end_time` as 11pm **UTC** >> subtracts 5 hours to get to 6pm **CDT**
   3. [Consumer] Browser returns current time of 6:30pm **CDT**
   4. [Consumer] Displays event as past
3. User visits http://foodtrucks.codeforeauclaire.org/ at 6:30pm on [Sunday, November 6](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=dst+2016) (after DST change)
   1. [Drupal] API returns `end_time` of 6pm
   2. [Consumer] Browser interprets  `end_time` as 11pm **UTC** >> subtracts 5 hours to get to 7pm **CST**
   3. [Consumer] Browser returns current time of 6:30pm **CST**
   4. [Consumer] Displays event as not past

Notice we're on [CDT right now and will be on CST later](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Is+it+CDT+or+CST%3F)

> North America: [...] most places in this time zone are currently on summer time / daylight saving time and are observing CDT. [...]

**Edge cases**

There may be some weird edge cases around 2am on [Sunday, November 6](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=dst+2016) but we shouldn't worry about that level of detail for Eau Claire Food Trucks.

**Comment by AnthonyAstige** [comment]
@Lowell20 Thanks for catching this and pointing out to me again, I think/hope my logic and patch above got it right this time.
