### ISSUE TITLE
[Drupal] Document API

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#48]
The API is solidifying and I figure it should have some light documentation for future maintenance. A couple gotcha examples which should be made clear (either explicitly or implicitly):
- `/api/events/2016-06-02` filters by `start_date`, it's possible the `end_date` returned is the next day
- Returned `start_date` and `end_date` are exactly as they are entered by venders with no timezone adjustments (assumed to be local Eau Claire time already DST adjusted)

**Comment by Lowell20** [comment]
- `/api/events` returns details of all events with their associate food trucks nested
- `/api/vendors` returns details for all vendor food trucks
- `/api/events/yyyy-mm-dd` returns only events with the same `start_time`, ignoring the `Thh:mm:ss` portion of the returned `start_time`

### Events
- Returned `uuid` is the unique identifier
- Returned `start_time` is exactly as they are entered by vendors with no timezone adjustments (assumed to be local Eau Claire time already DST adjusted)
- Returned `end_time` is simply offset by adding the `duration` entered by vendor to the `start_time`
- Returned `description`
- Returned `lat` is latitude 
- Returned `lng` is longitude 
- Returned `#` are the Vendor Food Truck(s) associated with the Event

### Vendor Food Trucks
- Returned `uuid` is the unique identifier
- Returned `title`
- Returned `description`
- Returned `logo` is the full `http(s)` url to the logo
- Returned `website_url` is a full `http(s)` url
- Returned `facebook_url` is a full `http(s)` url
- Returned `twitter_name` should be an `@twitter-name` value
- Returned `telephone_number` should be a telephone number

**Comment by Lowell20** [comment]
I've been updating the README.md
we can close this issue now, right, it's getting outdated anyway
