### ISSUE TITLE
[Drupal] Turn registration & Facebook login back on (They're no longer on login page?)

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#49]
![screenshot from 2016-06-01 17-38-35](https://cloud.githubusercontent.com/assets/236039/15728025/af215fc8-281f-11e6-97bc-cf6a31584379.png)

**Comment by Lowell20** [comment]
meh?

somehow this is fixed, please reopen if you notice them gone again

**Comment by Lowell20** [comment]
eeks, they are gone again
I really have no idea why they are gone, but will investigate

**Comment by Lowell20** [comment]
solved with 403 module, the previous redirect method failing us
