### ISSUE TITLE
[Drpual] Triage misc #2

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#50]
I didn't do a real QA round, just some things I noticed when using the [Drupal] site.  It's getting closer~
#### 1. Can we easily add another field by duration for minutes 00 15 30 45?

![can we easily add another field by duration for minutes 00 15 30 45](https://cloud.githubusercontent.com/assets/236039/15729478/26db3bf6-282a-11e6-8136-7c5488a046bb.png)
#### 2. my account section navigation needs work i notice offhand quickly view doesn t show anything the word edit doesn t make sense clicking my food trucks gets rid of menu i don t know why there s a title food

![my account section navigation needs work i notice offhand quickly view doesn t show anything the word edit doesn t make sense clicking my food trucks gets rid of menu i don t know why there s a title food](https://cloud.githubusercontent.com/assets/236039/15729479/26db3e12-282a-11e6-9588-14e180ea9930.png)
#### 3. on my account page but it s not highlighted red in the header

![on my account page but it s not highlighted red in the header](https://cloud.githubusercontent.com/assets/236039/15729477/26dae75a-282a-11e6-9b47-3ce27fb1de1d.png)

**Comment by Lowell20** [comment]
food is just your logged in name

**Comment by Lowell20** [comment]
created the minutes duration field, have not styled yet. will wait for more feedback for that

color the `my account` menu item red whenever when on the user and truck pages

**Comment by AnthonyAstige** [comment]
Opened / re-assigned to self to confirm

**Comment by AnthonyAstige** [comment]
Spoke about this stuff a lot during meeting today and items fell out of discussion, closing.
