### ISSUE TITLE
[Drupal] Triage 2016-06-06

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#62]
Reminder of what we spoke about today, hopefully mostly quick fixes, open new issues for any lengthy leftovers.
#1

[Screencast::Don't restrict permission on events list page](https://files.slack.com/files-pri/T0FENTM7V-F1EKW2SF9/download/1._don_t_restrict_permission_on_events_list_page.swf)
#2

![2](https://cloud.githubusercontent.com/assets/236039/15844084/ef08f860-2c2c-11e6-9760-c1c851312ab6.png)
#3

![3](https://cloud.githubusercontent.com/assets/236039/15844100/095827b8-2c2d-11e6-9066-2220a07f2ebc.png)
#4

![4](https://cloud.githubusercontent.com/assets/236039/15844108/10f985d4-2c2d-11e6-85cc-669a665b4212.png)
#5

![5](https://cloud.githubusercontent.com/assets/236039/15844111/156d5b40-2c2d-11e6-9d24-0ef179accbc7.png)
#6

![6](https://cloud.githubusercontent.com/assets/236039/15844116/18d2c34c-2c2d-11e6-8037-40467def394e.png)
#7

![7](https://cloud.githubusercontent.com/assets/236039/15844117/1a5baa80-2c2d-11e6-9c7f-41151f6d351e.png)
#8

![8](https://cloud.githubusercontent.com/assets/236039/15844119/1e8a47ce-2c2d-11e6-81e7-9745e49b85d7.png)
#9

![9](https://cloud.githubusercontent.com/assets/236039/15844120/2141ffd4-2c2d-11e6-8fee-3d070cc15b5a.png)
#10

![10](https://cloud.githubusercontent.com/assets/236039/15844122/240d4534-2c2d-11e6-9eb8-fc9e95568f90.png)
#11

![11](https://cloud.githubusercontent.com/assets/236039/15844125/28139156-2c2d-11e6-9533-74b01c09cfcc.png)
#12

![12](https://cloud.githubusercontent.com/assets/236039/15844126/2ab2936c-2c2d-11e6-8386-040e9da71eab.png)

**Comment by Lowell20** [comment]
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12

**Comment by Lowell20** [comment]
I think all these are done,

**Comment by AnthonyAstige** [comment]
Sounds good.  No need to review these items specifically, any remaining issues or regressions will fall out of our next full review.
