### ISSUE TITLE
[Drupal] [JavaScript] Add Event: Magic validations

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#63]
We're planning to hack this validation into Drupal using JavaScript.
- [x] ~~1. Await #64 (Blocker) >>~~ Make submission fail if default lat/lng submitted (See screenshot 1 below)
- [x] 2. Make submission fail if start time after end time (See screenshot 2 below)
# Screenshots
## 1

![1](https://cloud.githubusercontent.com/assets/236039/15844160/71329d78-2c2d-11e6-9e26-a4329d39ed9f.png)
## 2

![2](https://cloud.githubusercontent.com/assets/236039/15844159/71320516-2c2d-11e6-9ccf-8ebfb9517c81.png)

**Comment by AnthonyAstige** [comment]
@Lowell20 - I figure the first step of this issue is for you, after than feel free to hand off.

**Comment by AnthonyAstige** [comment]
@Lowell20 - Whoops wrong issue, apologies for the noise.  Please disregard last comment.

**Comment by AnthonyAstige** [comment]
@Lowell20 Take this on if you want, or feel free to hand off. If you want to hand this off, let us know where's the best place in the Drupal code to make these changes or add a file with JavaScript for the add/edit event page.

**Comment by Lowell20** [comment]
there is a js folder in the theme, I will wire it up so that it is included in the page load.
Let's call it createEvent.js
web/themes/custom/foodtrucktheme/js/createEvent.js
39f9efb
