### ISSUE TITLE
[Drupal] [JavaScript] Map customizations

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#64]
- [x] 1. Copy map module into our repository so we can edit it
- [x] 2. Select all when click address (so easy to type a different address) (See screenshot 2 below)
- [x] 3. Put LatLng in address field in various circumstances (See screenshot 3 below)
- [x] 4. Unblock #63
# Screenshots
## 2

![2](https://cloud.githubusercontent.com/assets/236039/15844313/d701e630-2c2e-11e6-8cbd-572ce70f9cc9.png)
## 3

![3](https://cloud.githubusercontent.com/assets/236039/15844315/d8775982-2c2e-11e6-8f41-ceec245274d7.png)

**Comment by AnthonyAstige** [comment]
@Lowell20 This is the issue we definitely need your help with in getting started as noted in #1 above.  After that feel free to hand off.

**Comment by AnthonyAstige** [comment]
@Lowell20 What commit was 1. above done in, and/or what code should be edited for this?

**Comment by Lowell20** [comment]
moved in geolocation module in this commit
efb46255c03036445d4ee132f7b16910c65dc4cf
it is in the web/modules/custom folder

**Comment by AnthonyAstige** [comment]
@Lowell20 

I made a small change in a7d425ced2a50f0df2b876d4ba95c149a4040985, but I had to hack it in without a plugin API.

While I think it would be possible to achieve `3.` in this issue and #63-1 by continued hacking, it would probably be easier and more maintainable with a proper plugin API.

Is there such an API / plugin documentation?  Or as I think I remember discussing, do you think it's a good idea to fork the map plugin since it's relatively new?

**Comment by AnthonyAstige** [comment]
@Lowell20 Whoops looks like you did fork it and I was in the wrong context.  I see code now in `/root/foodtrucks/drupal-project/web/modules/custom/geolocation` which is presumably the module fork.

**Comment by Lowell20** [comment]
The first approach that I want to try is to let you hack the module however you need. 
Then i will make a patch out of your changes so that we can apply that patch to the original module.

**Comment by AnthonyAstige** [comment]
3 done @ 91325ed37ff055ad306a89b734ff3e7471f12865.

@Lowell20 This changes the default behaviour of the original module quite a bit. Now all input is coerced into latLng as screenshot 3. above notes.  Your call if it's closer to the intention of that plugin.
