### ISSUE TITLE
[Drupal] Triage vendor UI

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#68]
@aaronsalmon - We didn't write a lot down as we expected to be obvious to you as you work on things.
- Hard block: ~~#67~~
- Maybe block: ~~#75~~
- Soft block: ~~#73~~, ~~#83~~

**Comment by Lowell20** [comment]
Just tested and looks all good, with compass watch and caching disabled

ping

**Comment by AnthonyAstige** [comment]
[README.md](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/README.md) instructions updated for easy 'food' user login in `4.ii.`

![screenshot from 2016-06-11 16-29-20](https://cloud.githubusercontent.com/assets/236039/15987566/ac32676a-2ff1-11e6-90b6-9ba8f533e24b.png)
