### ISSUE TITLE
[Drupal] Style Add Food Truck warning

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#69]
@Lowell20 Do what you can, then hand this to @aaronsalmon 

![2016-06-06_1913](https://cloud.githubusercontent.com/assets/236039/15844457/205c89c4-2c30-11e6-8843-c46286f7244c.png)

**Comment by Lowell20** [comment]
I changed to warning type of notification, I think Aaron will apply some more styling

**Comment by aaronsalmon** [comment]
the new default yellow message is a good change!
