### ISSUE TITLE
[Drupal] Style start time/minute

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#70]
@Lowell20 Do what you can easily, then hand to @aaronsalmon 

![2016-06-06_2001](https://cloud.githubusercontent.com/assets/236039/15844477/43d8b9c2-2c30-11e6-8b4d-77a4123ab521.png)

**Comment by Lowell20** [comment]
I will try to remove these on form generation, otherwise we must use css. There is no drupal ui for hiding labels in this form.

**Comment by Lowell20** [comment]
The start minute and end minute labels have been removed

**Comment by aaronsalmon** [comment]
styled
