### ISSUE TITLE
[Consumer] Style code up to Standard.js

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#71]
@levifelling - I set the code to [StandardJS](http://standardjs.com/) (Don't worry, you get S P A C E S :P) and I notice little things are getting out of sync in foodtrucks/consumer-ui/js/index.js

If you want a hand setting up your editor to adhere to the styles I can try to figure that out with you at the next meeting.  It looks like there's a simple `npm install standard` to run `standard` and check on the shell (I use syntastic in vim via eslint, hence the [.eslintrc.js](https://github.com/codeforeauclaire/foodtrucks/blob/master/consumer-ui/.eslintrc.js) file).

This isn't urgent (noton MVP milestone)

**Comment by levifelling** [comment]
I have this setup now using [SublimeLInter](http://jonathancreamer.com/setup-eslint-with-es6-in-sublime-text/).

**Comment by AnthonyAstige** [comment]
Perfect, thanks.  I see https://github.com/codeforeauclaire/foodtrucks/commit/a80689aa054abc29133b7ffb7e0169af6e1c2216 and it's all passing for me too now :)
