### ISSUE TITLE
[Consumer] Document MVP issues missed 2016-06-06

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#72]
@levifelling - I didn't get to write down [Consumer] issues until just now, and I figure you may remember a couple things I forgot. I know there wasn't too much though, so I may have gotten everything we spoke about.

You can see all the relevant issues by [searching issues for "is:open milestone:MVP consumer in:title"](https://github.com/codeforeauclaire/foodtrucks/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3AMVP+consumer++in%3Atitle+)

**Comment by levifelling** [comment]
I added #78, other wise I think everything is accounted for.
