### ISSUE TITLE
[Drupal] vendor api URL fields

### ISSUE THREAD

**Issue by levifelling** [codeforeauclaire/foodtrucks#74]
http://vendors.foodtrucks.codeforeauclaire.org/api/vendors

{
  website_url: "website.com",
  facebook_url: "facebook.com"
}

@Lowell20 does the backend do any validation on the user entered URLs? It would be preferable to return a full URL including the protocol `http://` or `https://` so the client application doesn't need to do any guesswork to convert the value to a URL.

**Comment by Lowell20** [comment]
Sadly no. It was decided last night to use plain text fields without any validation. Also be wary of scripts and html :-(

**Comment by Lowell20** [comment]
Please reopen this issue if we are going to change the current behavior of these being simple text entry fields
