### ISSUE TITLE
[Drupal] Confirm VMS install functional

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#81]
Lowell merged #80 then closed #73 and closed #75.  Test with [normal instructions](https://github.com/codeforeauclaire/foodtrucks/tree/master/drupal-project#vms-easy-setup-development-environment), if all good leave those prior issues closed, otherwise think about re-opening.

If / when all good unblock #67.

**Comment by Lowell20** [comment]
Just tested and looks all good, with compass watch and caching disabled

**Comment by AnthonyAstige** [comment]
Note to self: As Lowell noted above, the site loads when I just tried it too.  It appears issues relating to #75 (packages) are resolved. There are some other issues as I can't find login link, perhaps a config (close to but not quite #73).  Leaving this closed.
