### ISSUE TITLE
[Drupal] VMS: Fix login >> update instructions

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#83]
- ~~[ ] 0. Await menus (per Lowell's comment "..., menus and links are next" / blocked by #62)~~
- ~~[ ] 1. Fix: I don't see where to login when making a new foodtruck VMS~~
- [x] 2. Update [README.md](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/README.md) to login as 'food' user (Moved in from #67)
- [x] 2.5 Test [README.md](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/README.md) update works on new VMS
- [x] 3. Re-ping #68 citing new instructions

**Screenshot (don't see where to login)**

![2016-06-10_2210](https://cloud.githubusercontent.com/assets/236039/15982818/377fb844-2f58-11e6-8ef0-8616977b4f01.png)

**Comment by Lowell20** [comment]
I am thinking the current instructions to login as admin are right on. 
No need to login as any user, like 'food'
I think this issue is resolved

**Comment by AnthonyAstige** [comment]
I would like UI work (by Aaron in #68 in this case) to be done from the same context as a user of type "vendor".  A user of type "admin" has a different view than a vendor (Extra menus, etc), which can throw off the design process (and depending on Drupal's internals promote poor css coding / bugs). That said, it sounds like work can be done right now as is, so if it poses a major obstacle to implementation, we can take this out of the MVP milestone. Re-assigning to both me and Lowell to discuss at next in person meeting.

**Comment by Lowell20** [comment]
Yes, and as admin, you can create accounts, assign permissions, set passwords, you can do pretty much anything you need depending on what kind of user access you need

**Comment by AnthonyAstige** [comment]
A VMS is quick and temporary. The less steps needed each instantiation the better.

I believe the recent sql dump already includes the food user.

Why not provide an easy way to login with it on a vms instance?

**Comment by Lowell20** [comment]
right, username is food, and password is truck. but that may change with another db dump
Looks like we also have junk, junkone, junktwo, and Anthony users

**Comment by AnthonyAstige** [comment]
> but that may change with another db dump

I hope that we continue to have a vendor to login with (albeit different username / password).

On my last VMS foodtruck instantiation I saw no way to login even when knowing a username / password ([original screenshot](https://cloud.githubusercontent.com/assets/236039/15982818/377fb844-2f58-11e6-8ef0-8616977b4f01.png)).

Alternatively / additionally, is there a very simple 'login as' functionality in Drupal when logged in as admin?

**Comment by Lowell20** [comment]
Aha, I see what you are getting at. I've been getting vms working, menus and links are next

**Comment by AnthonyAstige** [comment]
Cool, good we understand each other now :)

I've noted this as blocked by #62 as I think menu stuff is in there.

**Comment by Lowell20** [comment]
actually, just go to /user to login

**Comment by AnthonyAstige** [comment]
Perfect, I got everything else needed here done now, thanks :)
