### ISSUE TITLE
API Endpoints are redirecting to login

### ISSUE THREAD

**Issue by levifelling** [codeforeauclaire/foodtrucks#87]
http://vendors.foodtrucks.codeforeauclaire.org/api/events
http://vendors.foodtrucks.codeforeauclaire.org/api/vendors

The above API endpoints are returning a `http status 302` and redirecting to http://vendors.foodtrucks.codeforeauclaire.org/user/login

My expectation is API endpoints would be publicly accessible.

**Comment by Lowell20** [comment]
Lol, that's hilarious. Fixing right away
