### ISSUE TITLE
[Consumer] Map markers should have indicate if the event is in the past, future or currently active.

### ISSUE THREAD

**Issue by aaronsalmon** [codeforeauclaire/foodtrucks#9]
When looking a the current day, I may see map markers for truck events that happened earlier in the day, events that are happening now, and events that are happening later in the day.  

i'll do a quick mockup for this - first

**Comment by AnthonyAstige** [comment]
Related from today's conversation: For the MVP each bubble on the map is going to be a single event. This concept relies on #17.

Simple UI solution for this issue at the map level might be different colored icons. Perhaps a legend to explain, but I'm unsure if it's worth the attention cost.

**Comment by AnthonyAstige** [comment]
@aaronsalmon As just noted in https://github.com/codeforeauclaire/foodtrucks/issues/5 I think your wire frames may apply here too.

**Comment by AnthonyAstige** [comment]
Done by Levi as noted in comment above.  Can't test live data, but confirmed with his test data as shown attached.

Closing.
![2016-05-23_2014](https://cloud.githubusercontent.com/assets/236039/15489175/10a3816c-2123-11e6-844e-891d681dbfc8.png)
