### ISSUE TITLE
[Drupal] Show all events for all accessible trucks 

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#97]
If this isn't easy, remove MVP milestone.

![2016-06-13_1633](https://cloud.githubusercontent.com/assets/236039/16167526/a7adfbcc-34bb-11e6-89d2-20e79d16843d.png)

**Comment by Lowell20** [comment]
554ddfa
initial test look good, please reopen if it doesn't work as expected
